[package]
name = "opentelemetry-types"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false

[features]
default = ["traces", "metrics", "logs"]
traces = []
metrics = []
logs = []

[dependencies]
prost = "0.12.4"

[build-dependencies]
prost-build = "0.12.4"