[package]
name = "opentelemetry-types"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[features]
default = ["traces", "metrics", "logs"]
traces = []
metrics = []
logs = []

[dependencies]
prost = "0.11.0"

[build-dependencies]
prost-build = "0.11.1"